# lightning.pytorch==2.0.0
seed_everything: 1111
trainer:
  default_root_dir: lightning_logs/flava/fhm/normal
  accelerator: gpu
  devices: 1
  max_epochs: 30
  accumulate_grad_batches: 1
  enable_checkpointing: True
  callbacks: 
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: checkpoints/flava/fhm/normal
        monitor: label_validate_auroc
        mode: max
        save_top_k: 1
        every_n_epochs: 1
        save_last: True
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: label_validate_auroc
        patience: 5
        mode: max
  
model:
  class_path: models.flava.FlavaClassificationModel
  init_args:
    model_class_or_path: facebook/flava-full
    cls_dict: {
      "label": 2
    }
data:
  class_path: datamodules.VLImagesDataModule
  init_args:
    tokenizer_class_or_path: facebook/flava-full
    frcnn_class_or_path: None
    image_dirs: {
      train: /Scratch/mingshan/datasets/fhm/images/img/,
      validate: /Scratch/mingshan/datasets/fhm/images/img/,
      test: /Scratch/mingshan/datasets/fhm/images/img/,
      predict: /Scratch/mingshan/datasets/fhm/images/img/
    }
    annotation_filepaths: {
      train: /Scratch/mingshan/datasets/fhm_normal/annotations/train.jsonl,
      validate: /Scratch/mingshan/datasets/fhm_normal/annotations/dev_seen.jsonl,
      test: /Scratch/mingshan/datasets/fhm_normal/annotations/dev_seen.jsonl,
      predict: /Scratch/mingshan/datasets/fhm_normal/annotations/dev_seen.jsonl
    }
    shuffle_train: True
    labels:
    - label
    batch_size: 32