# lightning.pytorch==2.0.0
seed_everything: 1111
# ckpt_path: checkpoints/visualbert_features/fhm/normal/visualbert_epochs30_date2306.ckpt
trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 30
  accumulate_grad_batches: 1
  enable_checkpointing: True
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: lightning_logs/
      name: fhm-finegrained
      version: visualbert_epochs30_date2306
      default_hp_metric: false
  callbacks: 
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: checkpoints/visualbert_features/fhm/normal
        filename: visualbert_epochs30_date2306
        monitor: label_validate_auroc
        mode: max
        save_top_k: 1
        every_n_epochs: 1
        save_last: True
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: label_validate_auroc
        patience: 5
        mode: max
model:
  class_path: models.visualbert.VisualBertClassificationModel
  init_args:
    model_class_or_path: uclanlp/visualbert-vqa-coco-pre
    cls_dict: {
      "label": 2
    }
data:
  class_path: datamodules.modules.FasterRCNNDataModule
  init_args:
    tokenizer_class_or_path: bert-base-uncased
    dataset_class: datamodules.datasets.fhm.FasterRCNNDataset
    feats_dirs: {
      train: /mnt/sda/datasets/memes/fhm/features/unc-nlp/frcnn-vg-finetuned,
      validate: /mnt/sda/datasets/memes/fhm/features/unc-nlp/frcnn-vg-finetuned,
      test: /mnt/sda/datasets/memes/fhm/features/unc-nlp/frcnn-vg-finetuned,
      predict: /mnt/sda/datasets/memes/fhm/features/unc-nlp/frcnn-vg-finetuned,
    }
    annotation_filepaths: {
      train: /mnt/sda/datasets/memes/fhm/annotations/train.jsonl,
      validate: /mnt/sda/datasets/memes/fhm/annotations/dev_seen.jsonl,
      test: /mnt/sda/datasets/memes/fhm/annotations/test_unseen.jsonl,
      predict: /mnt/sda/datasets/memes/fhm/annotations/test_unseen.jsonl,
    }
    auxiliary_dicts: {}
    shuffle_train: True
    batch_size: 32
    labels:
    - label
    num_workers: 8
