# lightning.pytorch==2.0.0
seed_everything: 1111
trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 30
  accumulate_grad_batches: 1
  enable_checkpointing: True
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: lightning_logs/
      name: fhm-finegrained
      version: visualbert_epochs30_date2306
      default_hp_metric: false
  callbacks: 
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: checkpoints/visualbert_images/fhm/normal
        filename: visualbert_epochs30_date2306
        monitor: label_validate_auroc
        mode: max
        save_top_k: 1
        every_n_epochs: 1
        save_last: True
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: label_validate_auroc
        patience: 5
        mode: max

model:
  class_path: models.visualbert.VisualBertClassificationModel
  init_args:
    model_class_or_path: uclanlp/visualbert-vqa-coco-pre
    cls_dict: {
      "label": 2
    }
data:
  class_path: datamodules.modules.ImagesDataModule
  init_args:
    tokenizer_class_or_path: bert-base-uncased
    dataset_class: datamodules.datasets.fhm.ImagesDataset
    frcnn_class_or_path: unc-nlp/frcnn-vg-finetuned
    image_dirs: {
      train: /mnt/sdb/aditi/hateful_memes/hateful_memes/img/,
      validate: /mnt/sdb/aditi/hateful_memes/hateful_memes/img/,
      test: /mnt/sdb/aditi/hateful_memes/hateful_memes/img/,
      predict: /mnt/sdb/aditi/hateful_memes/hateful_memes/img/,
    }
    annotation_filepaths: {
      train: /mnt/sdb/aditi/hateful_memes/hateful_memes/train.jsonl,
      validate: /mnt/sdb/aditi/hateful_memes/hateful_memes/dev_seen.jsonl,
      test: /mnt/sdb/aditi/datasets/fhm/annotations/test.jsonl,
      predict: /mnt/sdb/aditi/datasets/fhm/annotations/dev_seen.jsonl
    }
    auxiliary_dicts: {}
    shuffle_train: True
    batch_size: 4
    labels:
    - label
    num_workers: 8