accelerator: cuda
max_epochs: 1
limit_train_batches: 1
limit_val_batches: 1
accumulate_grad_batches: 1
enable_checkpointing: True
logger:
  _target_: lightning.pytorch.loggers.TensorBoardLogger
  save_dir: lightning_logs
  name: ${experiment_name}/${hydra:job.override_dirname}
  default_hp_metric: false
callbacks: 
  - _target_: lightning.pytorch.callbacks.ModelCheckpoint
    dirpath: ${hydra:runtime.output_dir}
    monitor: ${monitor_metric}
    mode: ${monitor_mode}
    save_top_k: ${save_top_ks}
    save_weights_only: true
    every_n_epochs: 1
    save_last: True
  - _target_: lightning.pytorch.callbacks.EarlyStopping
    monitor: ${monitor_metric}
    patience: 5
    mode: ${monitor_mode}