# lightning.pytorch==2.0.0
seed_everything: 1111
trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 30
  accumulate_grad_batches: 1
  enable_checkpointing: True
  callbacks: 
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: checkpoints/flava/fhm/hate
        monitor: hate_validate_auroc
        mode: max
        save_top_k: 1
        every_n_epochs: 1
        save_last: True
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: hate_validate_auroc
        patience: 5
        mode: max
  
model:
  class_path: models.flava.FlavaClassificationModel
  init_args:
    model_class_or_path: facebook/flava-full
    cls_dict: {
      "hate": 2
    }
data:
  class_path: datamodules.modules.ImagesDataModule
  init_args:
    tokenizer_class_or_path: facebook/flava-full
    frcnn_class_or_path: None
    dataset_class: datamodules.datasets.fhm_finegrained.ImagesDataset
    image_dirs: {
      train: /mnt/sda/datasets/memes/fhm/images/img/,
      validate: /mnt/sda/datasets/memes/fhm/images/img/,
      test: /mnt/sda/datasets/memes/fhm/images/img/,
      predict: /mnt/sda/datasets/memes/fhm/images/img/
    }
    annotation_filepaths: {
      train: /mnt/sda/datasets/memes/fhm_finegrained/annotations/train.jsonl,
      validate: /mnt/sda/datasets/memes/fhm_finegrained/annotations/dev_seen.jsonl,
      test: /mnt/sda/datasets/memes/fhm_finegrained/annotations/dev_seen.jsonl,
      predict: /mnt/sda/datasets/memes/fhm_finegrained/annotations/dev_seen.jsonl
    }
    auxiliary_dicts: {
      # "caption": "/mnt/sda/datasets/memes/fhm/captions/fhm_clean_captions.pkl"
    }
    shuffle_train: True
    labels:
    - hate
    batch_size: 4