# lightning.pytorch==2.0.0
seed_everything: 1111
trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 30
  accumulate_grad_batches: 1
  enable_checkpointing: True
  callbacks: 
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: checkpoints/lxmert_images/fhm/hate
        monitor: hate_validate_auroc
        mode: max
        save_top_k: 1
        every_n_epochs: 1
        save_last: True
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: hate_validate_auroc
        patience: 5
        mode: max

model:
  class_path: models.lxmert.LxmertClassificationModel
  init_args:
    model_class_or_path: unc-nlp/lxmert-base-uncased
    cls_dict: {
      "hate": 2
    }
data:
  class_path: datamodules.modules.ImagesDataModule
  init_args:
    tokenizer_class_or_path: unc-nlp/lxmert-base-uncased
    dataset_class: datamodules.datasets.fhm_finegrained.ImagesDataset
    frcnn_class_or_path: unc-nlp/frcnn-vg-finetuned
    image_dirs: {
      train: /mnt/sda/datasets/memes/fhm/images/img,
      validate: /mnt/sda/datasets/memes/fhm/images/img,
      test: /mnt/sda/datasets/memes/fhm/images/img,
      predict: /mnt/sda/datasets/memes/fhm/images/img,
    }
    annotation_filepaths: {
      train: /mnt/sda/datasets/memes/fhm_finegrained/annotations/train.json,
      validate: /mnt/sda/datasets/memes/fhm_finegrained/annotations/dev_seen.json,
      test: /mnt/sda/datasets/memes/fhm_finegrained/annotations/test.jsonl,
      predict: /mnt/sda/datasets/memes/fhm_finegrained/annotations/test.jsonl,
    }
    auxiliary_dicts: {}
    shuffle_train: True
    batch_size: 4
    labels:
    - hate
    num_workers: 8