# lightning.pytorch==2.0.0
seed_everything: 1111
trainer:
  default_root_dir: lightning_logs/bart/mami
  accelerator: gpu
  devices: 1
  max_epochs: 30
  accumulate_grad_batches: 1
  enable_checkpointing: True
  callbacks: 
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: checkpoints/bart/mami
        monitor: hate_validate_auroc
        mode: max
        save_top_k: 1
        every_n_epochs: 1
        save_last: True
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: hate_validate_auroc
        patience: 5
        mode: max
model:
  class_path: models.bart.BARTCasualModel
  init_args:
    model_class_or_path: facebook/bart-large
    labels:
    - shaming
    - misogynous
    - objectification
    - violence
    - stereotype
    label2word: {
      0: "no",
      1: "yes"
    }
data:
  class_path: datamodules.LanguageDataModule
  init_args:
    tokenizer_class_or_path: facebook/bart-large
    annotation_filepaths: {
      # train: /mnt/sda/datasets/memes/mami/annotations/train.jsonl,
      # validate: /mnt/sda/datasets/memes/mami/annotations/validate.jsonl,
      # test: /mnt/sda/datasets/memes/mami/annotations/validate.jsonl,
      # predict: /mnt/sda/datasets/memes/mami/annotations/validate.jsonl
      train: /Scratch/datasets/mami/annotations/train.jsonl,
      validate: /Scratch/datasets/mami/annotations/test.jsonl,
      test: /Scratch/datasets/mami/annotations/test.jsonl,
      predict: /Scratch/datasets/mami/annotations/test.jsonl,
    }
    auxiliary_dicts: {}
    input_template: "question: is it hateful? context: {text}"
    output_template: "{label}</s>"
    label2word: {
      0: "no",
      1: "yes"
    }
    shuffle_train: True
    labels:
    - shaming
    - misogynous
    - objectification
    - violence
    - stereotype
    batch_size: 32
