# lightning.pytorch==2.0.0
seed_everything: 1111
trainer:
  default_root_dir: lightning_logs/flava/mami
  accelerator: gpu
  devices: 1
  max_epochs: 30
  accumulate_grad_batches: 1
  enable_checkpointing: True
  callbacks: 
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: checkpoints/flava/mami
        monitor: hate_validate_auroc
        mode: max
        save_top_k: 1
        every_n_epochs: 1
        save_last: True
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: hate_validate_auroc
        patience: 5
        mode: max
model:
  class_path: models.flava.FlavaClassificationModel
  init_args:
    model_class_or_path: facebook/flava-full
    cls_dict: {
      "shaming": 2,
      "misogynous": 2,
      "objectification": 2,
      "violence": 2,
      "stereotype": 2
    }
data:
  class_path: datamodules.VLImagesDataModule
  init_args:
    tokenizer_class_or_path: facebook/flava-full
    frcnn_class_or_path: None
    image_dirs: {
      train: /Scratch/datasets/mami/images/img/train,
      validate: /Scratch/datasets/mami/images/img/test,
      test: /Scratch/datasets/mami/images/img/test,
      predict: /Scratch/datasets/mami/images/img/test,
    }
    annotation_filepaths: {
      train: /Scratch/datasets/mami/annotations/train.jsonl,
      validate: /Scratch/datasets/mami/annotations/test.jsonl,
      test: /Scratch/datasets/mami/annotations/test.jsonl,
      predict: /Scratch/datasets/mami/annotations/test.jsonl,
    }
    shuffle_train: True
    labels:
    - shaming
    - misogynous
    - objectification
    - violence
    - stereotype
    batch_size: 32