# lightning.pytorch==2.0.0
seed_everything: 1111
trainer:
  default_root_dir: lightning_logs/lxmert_features/mami
  accelerator: gpu
  devices: 1
  max_epochs: 30
  accumulate_grad_batches: 1
  enable_checkpointing: True
  callbacks: 
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: checkpoints/lxmert_features/mami
        monitor: hate_validate_auroc
        mode: max
        save_top_k: 1
        every_n_epochs: 1
        save_last: True
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: hate_validate_auroc
        patience: 5
        mode: max
model:
  class_path: models.lxmert.LxmertClassificationModel
  init_args:
    model_class_or_path: unc-nlp/lxmert-base-uncased
    cls_dict: {
      "shaming": 2,
      "misogynous": 2,
      "objectification": 2,
      "violence": 2,
      "stereotype": 2
    }
data:
  class_path: datamodules.VLFeaturesDataModule
  init_args:
    tokenizer_class_or_path: unc-nlp/lxmert-base-uncased
    feats_dirs: {
      train: /Scratch/datasets/mami/features/train/unc-nlp/frcnn-vg-finetuned,
      validate: /Scratch/datasets/mami/features/validate/unc-nlp/frcnn-vg-finetuned,
      test: /Scratch/datasets/mami/features/test/unc-nlp/frcnn-vg-finetuned,
      predict: /Scratch/datasets/mami/features/test/unc-nlp/frcnn-vg-finetuned,
    }
    annotation_filepaths: {
      train: /Scratch/datasets/mami/annotations/train.jsonl,
      validate: /Scratch/datasets/mami/annotations/test.jsonl,
      test: /Scratch/datasets/mami/annotations/test.jsonl,
      predict: /Scratch/datasets/mami/annotations/test.jsonl,
    }
    shuffle_train: True
    labels:
    - shaming
    - misogynous
    - objectification
    - violence
    - stereotype
    batch_size: 32
