# lightning.pytorch==2.0.0
seed_everything: 1111
trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 30
  accumulate_grad_batches: 1
  enable_checkpointing: True
  callbacks: 
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: checkpoints/t5/mami
        monitor: val_auroc
        mode: max
        save_top_k: 1
        every_n_epochs: 1
        save_last: True
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val_auroc
        patience: 5
        mode: max
model:
  class_path: models.t5.T5ClassificationModel
  init_args:
    model_class_or_path: t5-large
    labels:
    - shaming
    - misogynous
    - objectification
    - violence
    - stereotype
    label2word: {
      0: "no",
      1: "yes"
    }
data:
  class_path: datamodules.modules.TextDataModule
  init_args:
    tokenizer_class_or_path: t5-large
    dataset_class: datamodules.datasets.mami.TextDataset
    annotation_filepaths: {
      # train: /mnt/sda/datasets/memes/mami/annotations/train.jsonl,
      # validate: /mnt/sda/datasets/memes/mami/annotations/validate.jsonl,
      # test: /mnt/sda/datasets/memes/mami/annotations/validate.jsonl,
      # predict: /mnt/sda/datasets/memes/mami/annotations/validate.jsonl
      train: /mnt/sdb/aditi/MAMI/training/TRAINING/training.csv,
      validate: /mnt/sdb/aditi/MAMI/trial/Users/fersiniel/Desktop/MAMITOLABEL/TRIALDATASET/trial.csv,
      test: /mnt/sdb/aditi/MAMI/test/test/Test.csv,
      predict: /mnt/sdb/aditi/MAMI/test/test/Test.csv,
    }
    auxiliary_dicts: {}
    input_template: "question: is it hateful? context: {text}"
    output_template: "{label}</s>"
    label2word: {
      0: "no",
      1: "yes"
    }
    shuffle_train: True
    batch_size: 32
    labels:
    - shaming
    - misogynous
    - objectification
    - violence
    - stereotype
    num_workers: 8