job:
  config:
    override_dirname:
      exclude_keys:
        - experiment
        - action
run:
  dir: experiments/${experiment_name}
sweep:
  dir: experiments
  subdir: ${experiment_name}/${hydra.job.override_dirname}
  
job_logging:
  version: 1
  formatters:
    simple:
      format: '[%(levelname)s] - %(message)s'
  # handlers:
  #   console:
  #     class: logging.StreamHandler
  #     formatter: simple
  #     stream: ext://sys.stdout
  # root:
  #   handlers: [console]