# lightning.pytorch==2.0.0
seed_everything: 1111
trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 30
  accumulate_grad_batches: 1
  enable_checkpointing: True
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: lightning_logs/
      name: fhm-finegrained
      version: hostname_time_lr_batch_size
      default_hp_metric: false
  callbacks: 
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: checkpoints/bart/mami
<<<<<<< HEAD:configs/mami/bart.yaml
        filename: bart_epochs30_date2306
=======
>>>>>>> origin/main:configs/mami/subtask_b/bart.yaml
        monitor: val_auroc
        mode: max
        save_top_k: 1
        every_n_epochs: 1
        save_last: True
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val_auroc
        patience: 5
        mode: max
model:
  class_path: models.bart.BARTCasualModel
  init_args:
    model_class_or_path: facebook/bart-large
    labels:
    - shaming
    - objectification
    - violence
    - stereotype
    label2word: {
      0: "no",
      1: "yes"
    }
data:
  class_path: datamodules.modules.TextDataModule
  init_args:
    tokenizer_class_or_path: facebook/bart-large
    dataset_class: datamodules.datasets.mami.TextDataset
    annotation_filepaths: {
<<<<<<< HEAD:configs/mami/bart.yaml
      # train: /mnt/sda/datasets/memes/mami/annotations/train.jsonl,
      # validate: /mnt/sda/datasets/memes/mami/annotations/validate.jsonl,
      # test: /mnt/sda/datasets/memes/mami/annotations/validate.jsonl,
      # predict: /mnt/sda/datasets/memes/mami/annotations/validate.jsonl
      train: /mnt/sdb/aditi/MAMI/training/TRAINING/training.csv,
      validate: /mnt/sdb/aditi/MAMI/trial/Users/fersiniel/Desktop/MAMITOLABEL/TRIALDATASET/trial.csv,
      test: /mnt/sdb/aditi/MAMI/test/test/Test.csv,
      predict: /mnt/sdb/aditi/MAMI/test/test/Test.csv,
=======
      train: /mnt/sda/datasets/memes/mami/annotations/training.csv,
      validate: /mnt/sda/datasets/memes/mami/annotations/trial.csv,
      test: /mnt/sda/datasets/memes/mami/annotations/Test.csv,
      predict: /mnt/sda/datasets/memes/mami/annotations/Test.csv
>>>>>>> origin/main:configs/mami/subtask_b/bart.yaml
    }
    auxiliary_dicts: {}
    input_template: "question: is it misogynous? context: {text}"
    output_template: "{label}</s>"
    label2word: {
      0: "no",
      1: "yes"
    }
    shuffle_train: True
    labels:
    - shaming
    - objectification
    - violence
    - stereotype
    batch_size: 32
    num_workers: 8
