annotation_filepaths:
  train: /mnt/sda/mshee/datasets/memes/fhm/annotations/train.jsonl
  validate: /mnt/sda/mshee/datasets/memes/fhm/annotations/dev_seen.jsonl
  test: /mnt/sda/mshee/datasets/memes/fhm/annotations/test_seen.jsonl
  predict: /mnt/sda/mshee/datasets/memes/fhm/annotations/test_seen.jsonl

image_dirs:
  train: /mnt/sda/mshee/datasets/memes/fhm/images/img
  validate: /mnt/sda/mshee/datasets/memes/fhm/images/img
  test: /mnt/sda/mshee/datasets/memes/fhm/images/img
  predict: /mnt/sda/mshee/datasets/memes/fhm/images/img

auxiliary_dicts:
  train: {}
  validate: {}
  test: {}
  predict: {}

feats_dir:
  train: null
  validate: null
  test: null
  predict: null

dataset_class: ???
text_template: ???
labels: ???