fhm:
  annotation_filepaths:
    train: /mnt/data1/datasets/memes/fhm/annotations/train.jsonl
    validate: /mnt/data1/datasets/memes/fhm/annotations/dev_seen.jsonl
    test: /mnt/data1/datasets/memes/fhm/annotations/test_seen.jsonl
    predict: /mnt/data1/datasets/memes/fhm/annotations/test_seen.jsonl

  image_dirs:
    train: /mnt/data1/datasets/memes/fhm/images/img
    validate: /mnt/data1/datasets/memes/fhm/images/img
    test: /mnt/data1/datasets/memes/fhm/images/img
    predict: /mnt/data1/datasets/memes/fhm/images/img

  auxiliary_dicts:
    train: 
      caption: /mnt/data1/datasets/memes/fhm/captions/img/ofa-large-caption
    validate:
      caption: /mnt/data1/datasets/memes/fhm/captions/img/ofa-large-caption
    test: 
      caption: /mnt/data1/datasets/memes/fhm/captions/img/ofa-large-caption
    predict: 
      caption: /mnt/data1/datasets/memes/fhm/captions/img/ofa-large-caption

  feats_dir:
    train: null
    validate: null
    test: null
    predict: null

  dataset_class: ???
  text_template: ???
  labels: ???
