annotation_filepaths:
  train: /mnt/sda/mshee/datasets/memes/fhm_finegrained/annotations/train.json
  validate: /mnt/sda/mshee/datasets/memes/fhm_finegrained/annotations/dev_seen.json
  test: /mnt/sda/mshee/datasets/memes/fhm_finegrained/annotations/dev_seen.json
  predict: /mnt/sda/mshee/datasets/memes/fhm_finegrained/annotations/test.jsonl

image_dirs:
  train: /mnt/sda/mshee/datasets/memes/fhm/images/img
  validate: /mnt/sda/mshee/datasets/memes/fhm/images/img
  test: /mnt/sda/mshee/datasets/memes/fhm/images/img
  predict: /mnt/sda/mshee/datasets/memes/fhm/images/img

feats_dirs:
  train: /mnt/sda/mshee/datasets/memes/fhm/features/unc-nlp/frcnn-vg-finetuned
  validate: /mnt/sda/mshee/datasets/memes/fhm/features/unc-nlp/frcnn-vg-finetuned
  test: /mnt/sda/mshee/datasets/memes/fhm/features/unc-nlp/frcnn-vg-finetuned
  predict: /mnt/sda/mshee/datasets/memes/fhm/features/unc-nlp/frcnn-vg-finetuned

auxiliary_dicts:
  train: {}
  validate: {}
  test: {}
  predict: {}

dataset_class: ???
text_template: ???
labels: ???
