harm_p:
  annotation_filepaths:
    train: /mnt/data1/datasets/memes/harmp/annotations/train_v1.jsonl
    validate: /mnt/data1/datasets/memes/harmp/annotations/val_v1.jsonl
    test: /mnt/data1/datasets/memes/harmp/annotations/test_v1.jsonl
    predict: /mnt/data1/datasets/memes/harmp/annotations/test_v1.jsonl

  image_dirs:
    train: /mnt/data1/datasets/memes/harmp/images/img_clean/harmeme_images_us_pol
    validate: /mnt/data1/datasets/memes/harmp/images/img_clean/harmeme_images_us_pol
    test: /mnt/data1/datasets/memes/harmp/images/img_clean/harmeme_images_us_pol
    predict: /mnt/data1/datasets/memes/harmp/images/img_clean/harmeme_images_us_pol

  auxiliary_dicts:
    train: 
      caption: /mnt/data1/datasets/memes/harmp/preprocessing/blip2_captions/harmeme_images_us_pol/
    validate:
      caption: /mnt/data1/datasets/memes/harmp/preprocessing/blip2_captions/harmeme_images_us_pol/
    test: 
      caption: /mnt/data1/datasets/memes/harmp/preprocessing/blip2_captions/harmeme_images_us_pol/
    predict: 
      caption: /mnt/data1/datasets/memes/harmp/preprocessing/blip2_captions/harmeme_images_us_pol/

  feats_dir:
    train: null
    validate: null
    test: null
    predict: null

  dataset_class: ???
  text_template: ???
  labels: ???
