annotation_filepaths:
  train: /mnt/sda/datasets/memes/harmemes/annotations/train.jsonl,
  validate: /mnt/sda/datasets/memes/harmemes/annotations/val.jsonl,
  test: /mnt/sda/datasets/memes/harmemes/annotations/test.jsonl,
  predict: /mnt/sda/datasets/memes/harmemes/annotations/test.jsonl,

image_dirs:
  train: /mnt/sda/datasets/memes/harmemes/images,
  validate: /mnt/sda/datasets/memes/harmemes/images,
  test: /mnt/sda/datasets/memes/harmemes/images,
  predict: /mnt/sda/datasets/memes/harmemes/images,

feats_dirs:
  train: /mnt/sda/datasets/memes/harmemes/features/unc-nlp/frcnn-vg-finetuned,
  validate: /mnt/sda/datasets/memes/harmemes/features/unc-nlp/frcnn-vg-finetuned,
  test: /mnt/sda/datasets/memes/harmemes/features/unc-nlp/frcnn-vg-finetuned,
  predict: /mnt/sda/datasets/memes/harmemes/features/unc-nlp/frcnn-vg-finetuned,

labels:
  intensity:
    - intensity
  target:
    - target
