harmeme:  
  annotation_filepaths:
    train: /mnt/data1/datasets/memes/harmeme/annotations/train.jsonl
    validate: /mnt/data1/datasets/memes/harmeme/annotations/val.jsonl
    test: /mnt/data1/datasets/memes/harmeme/annotations/test.jsonl
    predict: /mnt/data1/datasets/memes/harmeme/annotations/test.jsonl

  image_dirs:
    train: /mnt/data1/datasets/memes/harmeme/images/img
    validate: /mnt/data1/datasets/memes/harmeme/images/img
    test: /mnt/data1/datasets/memes/harmeme/images/img
    predict: /mnt/data1/datasets/memes/harmeme/images/img

  auxiliary_dicts:
    train: 
      caption: /mnt/data1/datasets/memes/harmeme/captions/deepfillv2/blip2-opt-6.7b-coco
    validate:
      caption: /mnt/data1/datasets/memes/harmeme/captions/deepfillv2/blip2-opt-6.7b-coco
    test: 
      caption: /mnt/data1/datasets/memes/harmeme/captions/deepfillv2/blip2-opt-6.7b-coco
    predict: 
      caption: /mnt/data1/datasets/memes/harmeme/captions/deepfillv2/blip2-opt-6.7b-coco
      
  feats_dir:
    train: null
    validate: null
    test: null
    predict: null

  dataset_class: ???
  text_template: ???
  labels: ???
