annotation_filepaths:
  train: /mnt/sda/mshee/datasets/memes/harmeme/annotations/train.jsonl
  validate: /mnt/sda/mshee/datasets/memes/harmeme/annotations/val.jsonl
  test: /mnt/sda/mshee/datasets/memes/harmeme/annotations/test.jsonl
  predict: /mnt/sda/mshee/datasets/memes/harmeme/annotations/test.jsonl

image_dirs:
  train: /mnt/sda/mshee/datasets/memes/harmeme/images
  validate: /mnt/sda/mshee/datasets/memes/harmeme/images
  test: /mnt/sda/mshee/datasets/memes/harmeme/images
  predict: /mnt/sda/mshee/datasets/memes/harmeme/images

feats_dirs:
  train: /mnt/sda/mshee/datasets/memes/harmeme/features/unc-nlp/frcnn-vg-finetuned
  validate: /mnt/sda/mshee/datasets/memes/harmeme/features/unc-nlp/frcnn-vg-finetuned
  test: /mnt/sda/mshee/datasets/memes/harmeme/features/unc-nlp/frcnn-vg-finetuned
  predict: /mnt/sda/mshee/datasets/memes/harmeme/features/unc-nlp/frcnn-vg-finetuned

auxiliary_dicts:
  train: {}
  validate: {}
  test: {}
  predict: {}

dataset_class: ???
text_template: ???
labels: ???
