latent_hatred:
  annotation_filepaths:
    train: /mnt/data1/datasets/hatespeech/latent_hatred/preprocessed/finaltrain.jsonl
    validate: /mnt/data1/datasets/hatespeech/latent_hatred/preprocessed/finalval.jsonl
    test: /mnt/data1/datasets/hatespeech/latent_hatred/preprocessed/finaltest.jsonl
    predict: /mnt/data1/datasets/hatespeech/latent_hatred/preprocessed/finaltest.jsonl

  auxiliary_dicts:
    train: 
      generated_implied_statement: /mnt/data1/datasets/hatespeech/latent_hatred/rationales/train
    validate: 
      generated_implied_statement: /mnt/data1/datasets/hatespeech/latent_hatred/rationales/val
    test: 
      generated_implied_statement: /mnt/data1/datasets/hatespeech/latent_hatred/rationales/test
    predict: 
      generated_implied_statement: /mnt/data1/datasets/hatespeech/latent_hatred/rationales/test
      
  feats_dir:
    train: null
    validate: null
    test: null
    predict: null

  dataset_class: ???
  text_template: ???
  labels: ???