mami:
  annotation_filepaths:
    train: /mnt/data1/datasets/memes/mami/annotations/train.jsonl
    validate: /mnt/data1/datasets/memes/mami/annotations/trial.jsonl
    test: /mnt/data1/datasets/memes/mami/annotations/test.jsonl
    predict: /mnt/data1/datasets/memes/mami/annotations/test.jsonl

  image_dirs:
    train: /mnt/data1/datasets/memes/mami/images/img/train
    validate: /mnt/data1/datasets/memes/mami/images/img/trial
    test: /mnt/data1/datasets/memes/mami/images/img/test
    predict: /mnt/data1/datasets/memes/mami/images/img/test

  auxiliary_dicts:
    train: 
      caption: /mnt/data1/datasets/memes/mami/captions/deepfillv2/train/blip2-opt-6.7b-coco
    validate:
      caption: /mnt/data1/datasets/memes/mami/captions/deepfillv2/trial/blip2-opt-6.7b-coco
    test: 
      caption: /mnt/data1/datasets/memes/mami/captions/deepfillv2/test/blip2-opt-6.7b-coco
    predict: 
      caption: /mnt/data1/datasets/memes/mami/captions/deepfillv2/test/blip2-opt-6.7b-coco

  feats_dir:
    train: null
    validate: null
    test: null
    predict: null

  dataset_class: ???
  text_template: ???
  labels: ???
