mami:
  annotation_filepaths:
    train: /mnt/data1/datasets/memes/mami/annotations/train.jsonl
    validate: /mnt/data1/datasets/memes/mami/annotations/trial.jsonl
    test: /mnt/data1/datasets/memes/mami/annotations/test.jsonl
    predict: /mnt/data1/datasets/memes/mami/annotations/test.jsonl

  image_dirs:
    train: /mnt/data1/datasets/memes/mami/images/img/train
    validate: /mnt/data1/datasets/memes/mami/images/img/trial
    test: /mnt/data1/datasets/memes/mami/images/img/test
    predict: /mnt/data1/datasets/memes/mami/images/img/test

  auxiliary_dicts:
    train: 
      interpretation: /mnt/data1/datasets/memes/mami/interpretations/train/InstructBLIP/prompt_5
    validate: 
      interpretation: /mnt/data1/datasets/memes/mami/interpretations/trial/InstructBLIP/prompt_5
    test: 
      interpretation: /mnt/data1/datasets/memes/mami/interpretations/test/InstructBLIP/prompt_5
    predict: 
      interpretation: /mnt/data1/datasets/memes/mami/interpretations/test/InstructBLIP/prompt_5

  feats_dir:
    train: null
    validate: null
    test: null
    predict: null

  dataset_class: ???
  text_template: ???
  labels: ???