annotation_filepaths:
  train: /mnt/sda/mshee/datasets/memes/mami/annotations/train.jsonl
  validate: /mnt/sda/mshee/datasets/memes/mami/annotations/trial.jsonl
  test: /mnt/sda/mshee/datasets/memes/mami/annotations/test.jsonl
  predict: /mnt/sda/mshee/datasets/memes/mami/annotations/test.jsonl

image_dirs:
  train: /mnt/sda/mshee/datasets/memes/mami/images/img/train
  validate: /mnt/sda/mshee/datasets/memes/mami/images/img/trial
  test: /mnt/sda/mshee/datasets/memes/mami/images/img/test
  predict: /mnt/sda/mshee/datasets/memes/mami/images/img/test

feats_dirs:
  train: /mnt/sda/mshee/datasets/memes/mami/features/train/unc-nlp/frcnn-vg-finetuned
  validate: /mnt/sda/mshee/datasets/memes/mami/features/validate/unc-nlp/frcnn-vg-finetuned
  test: /mnt/sda/mshee/datasets/memes/mami/features/test/unc-nlp/frcnn-vg-finetuned
  predict: /mnt/sda/mshee/datasets/memes/mami/features/test/unc-nlp/frcnn-vg-finetuned

auxiliary_dicts:
  train: {}
  validate: {}
  test: {}
  predict: {}

dataset_class: ???
text_template: ???
labels: ???