sbic:
  annotation_filepaths:
    train: /mnt/data1/datasets/memes/sbic/preprocessed/SBFv2.trn.jsonl
    validate: /mnt/data1/datasets/memes/sbic/preprocessed/SBFv2.dev.jsonl
    test: /mnt/data1/datasets/memes/sbic/preprocessed/SBFv2.tst.jsonl
    predict: /mnt/data1/datasets/memes/sbic/preprocessed/SBFv2.tst.jsonl

  auxiliary_dicts:
    train: 
      caption: null
    validate: 
      caption: null
    test: 
      caption: null
    predict: 
      caption: null

  feats_dir:
    train: null
    validate: null
    test: null
    predict: null

  dataset_class: ???
  text_template: ???
  labels: ???