# lightning.pytorch==2.0.0
seed_everything: 1111
trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 30
  accumulate_grad_batches: 1
  enable_checkpointing: True
  callbacks: 
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: checkpoints/flava/mami
        monitor: misogynous_validate_auroc
        mode: max
        save_top_k: 1
        every_n_epochs: 1
        save_last: True
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: misogynous_validate_auroc
        patience: 5
        mode: max
model:
  class_path: models.flava.FlavaClassificationModel
  init_args:
    model_class_or_path: facebook/flava-full
    cls_dict: {
      "misogynous": 2,
    }
data:
  class_path: datamodules.modules.ImagesDataModule
  init_args:
    tokenizer_class_or_path: facebook/flava-full
    frcnn_class_or_path: None
    dataset_class: datamodules.datasets.mami.ImagesDataset
    image_dirs: {
      train: /mnt/sda/datasets/memes/mami/images/img/train,
      validate: /mnt/sda/datasets/memes/mami/images/img/validate,
      test: /mnt/sda/datasets/memes/mami/images/img/test,
      predict: /mnt/sda/datasets/memes/mami/images/img/test
    }
    annotation_filepaths: {
      train: /mnt/sda/datasets/memes/mami/annotations/training.csv,
      validate: /mnt/sda/datasets/memes/mami/annotations/trial.csv,
      test: /mnt/sda/datasets/memes/mami/annotations/Test.csv,
      predict: /mnt/sda/datasets/memes/mami/annotations/Test.csv
    }
    auxiliary_dicts: {}
    shuffle_train: True
    labels:
    - misogynous
    batch_size: 32
    num_workers: 8