datasets:
  fhm:
    annotation_filepaths:
      {
        train: /mnt/sda/datasets/memes/fhm/annotations/train.jsonl,
        validate: /mnt/sda/datasets/memes/fhm/annotations/dev_seen.jsonl,
        test: /mnt/sda/datasets/memes/fhm/annotations/test_unseen.jsonl,
        predict: /mnt/sda/datasets/memes/fhm/annotations/test_unseen.jsonl,
      }
    image_dirs:
      {
        train: /mnt/sda/datasets/memes/fhm/images/img,
        validate: /mnt/sda/datasets/memes/fhm/images/img,
        test: /mnt/sda/datasets/memes/fhm/images/img,
        predict: /mnt/sda/datasets/memes/fhm/images/img,
      }
    feats_dirs:
      {
        train: /mnt/sda/datasets/memes/fhm/features/unc-nlp/frcnn-vg-finetuned,
        validate: /mnt/sda/datasets/memes/fhm/features/unc-nlp/frcnn-vg-finetuned,
        test: /mnt/sda/datasets/memes/fhm/features/unc-nlp/frcnn-vg-finetuned,
        predict: /mnt/sda/datasets/memes/fhm/features/unc-nlp/frcnn-vg-finetuned,
      }
    labels:
      - label

  fhm_finegrained:
    annotation_filepaths:
      {
        train: /mnt/sda/datasets/memes/fhm_finegrained/annotations/train.json,
        validate: /mnt/sda/datasets/memes/fhm_finegrained/annotations/dev_seen.json,
        test: /mnt/sda/datasets/memes/fhm_finegrained/annotations/dev_seen.json,
        predict: /mnt/sda/datasets/memes/fhm_finegrained/annotations/test.jsonl,
      }
    image_dirs:
      {
        train: /mnt/sda/datasets/memes/fhm/images/img,
        validate: /mnt/sda/datasets/memes/fhm/images/img,
        test: /mnt/sda/datasets/memes/fhm/images/img,
        predict: /mnt/sda/datasets/memes/fhm/images/img,
      }
    feats_dirs:
      {
        train: /mnt/sda/datasets/memes/fhm/features/unc-nlp/frcnn-vg-finetuned,
        validate: /mnt/sda/datasets/memes/fhm/features/unc-nlp/frcnn-vg-finetuned,
        test: /mnt/sda/datasets/memes/fhm/features/unc-nlp/frcnn-vg-finetuned,
        predict: /mnt/sda/datasets/memes/fhm/features/unc-nlp/frcnn-vg-finetuned,
      }
    labels:
      - hate
  harmemes:
    annotation_filepaths:
      {
        train: /mnt/sda/datasets/memes/harmemes/annotations/train.jsonl,
        validate: /mnt/sda/datasets/memes/harmemes/annotations/val.jsonl,
        test: /mnt/sda/datasets/memes/harmemes/annotations/test.jsonl,
        predict: /mnt/sda/datasets/memes/harmemes/annotations/test.jsonl,
      }
    image_dirs:
      {
        train: /mnt/sda/datasets/memes/harmemes/images,
        validate: /mnt/sda/datasets/memes/harmemes/images,
        test: /mnt/sda/datasets/memes/harmemes/images,
        predict: /mnt/sda/datasets/memes/harmemes/images,
      }
    feats_dirs:
      {
        train: /mnt/sda/datasets/memes/harmemes/features/unc-nlp/frcnn-vg-finetuned,
        validate: /mnt/sda/datasets/memes/harmemes/features/unc-nlp/frcnn-vg-finetuned,
        test: /mnt/sda/datasets/memes/harmemes/features/unc-nlp/frcnn-vg-finetuned,
        predict: /mnt/sda/datasets/memes/harmemes/features/unc-nlp/frcnn-vg-finetuned,
      }
    labels:
      intensity:
        - intensity
      target:
        - target
  mami:
    annotation_filepaths:
      {
        train: /mnt/sda/datasets/memes/mami/annotations/training.csv,
        validate: /mnt/sda/datasets/memes/mami/annotations/trial.csv,
        test: /mnt/sda/datasets/memes/mami/annotations/test.csv,
        predict: /mnt/sda/datasets/memes/mami/annotations/test.csv,
      }
    image_dirs:
      {
        train: /mnt/sda/datasets/memes/mami/images/img/train,
        validate: /mnt/sda/datasets/memes/mami/images/img/validate,
        test: /mnt/sda/datasets/memes/mami/images/img/test,
        predict: /mnt/sda/datasets/memes/mami/images/img/test,
      }
    feats_dirs:
      {
        train: /mnt/sda/datasets/memes/mami/features/train/unc-nlp/frcnn-vg-finetuned,
        validate: /mnt/sda/datasets/memes/mami/features/validate/unc-nlp/frcnn-vg-finetuned,
        test: /mnt/sda/datasets/memes/mami/features/test/unc-nlp/frcnn-vg-finetuned,
        predict: /mnt/sda/datasets/memes/mami/features/test/unc-nlp/frcnn-vg-finetuned,
      }
    labels:
      subtask_a:
        - misogynous
      subtask_b:
        - shaming
        - objectification
        - violence
        - stereotype
  harmp:
    annotation_filepaths:
      {
        train: /mnt/sda/datasets/memes/harmp/annotations/train.jsonl,
        validate: /mnt/sda/datasets/memes/harmp/annotations/val.jsonl,
        test: /mnt/sda/datasets/memes/harmp/annotations/test.jsonl,
        predict: /mnt/sda/datasets/memes/harmp/annotations/test.jsonl,
      }
    image_dirs:
      {
        train: /mnt/sda/datasets/memes/harmp/images,
        validate: /mnt/sda/datasets/memes/harmp/images,
        test: /mnt/sda/datasets/memes/harmp/images,
        predict: /mnt/sda/datasets/memes/harmp/images,
      }
    feats_dirs:
      {
        train: /mnt/sda/datasets/memes/harmp/features/unc-nlp/frcnn-vg-finetuned,
        validate: /mnt/sda/datasets/memes/harmp/features/unc-nlp/frcnn-vg-finetuned,
        test: /mnt/sda/datasets/memes/harmp/features/unc-nlp/frcnn-vg-finetuned,
        predict: /mnt/sda/datasets/memes/harmp/features/unc-nlp/frcnn-vg-finetuned,
      }
    labels:
      intensity:
        - intensity
      target:
        - target