trainers:
  bart:
    accelerator: gpu
    devices: 1
    max_epochs: 1
    accumulate_grad_batches: 1
    enable_checkpointing: True
    logger:
      class_path: lightning.pytorch.loggers.TensorBoardLogger
      init_args:
        save_dir: lightning_logs/
        name: fhm
        version: bart_tests
        default_hp_metric: false
    callbacks:
      - class_path: lightning.pytorch.callbacks.ModelCheckpoint
        init_args:
          dirpath: checkpoints/bart/fhm/normal
          filename: bart_tests
          monitor: val_auroc
          mode: max
          save_top_k: 1
          every_n_epochs: 1
          save_last: True
      - class_path: lightning.pytorch.callbacks.EarlyStopping
        init_args:
          monitor: val_auroc
          patience: 5
          mode: max
  flava:
      accelerator: gpu
      devices: 1
      max_epochs: 1
      accumulate_grad_batches: 1
      enable_checkpointing: True
      logger:
        class_path: lightning.pytorch.loggers.TensorBoardLogger
        init_args:
          save_dir: lightning_logs/
          name: fhm
          version: flava_tests
          default_hp_metric: false
      callbacks:
        - class_path: lightning.pytorch.callbacks.ModelCheckpoint
          init_args:
            dirpath: checkpoints/flava/fhm/normal
            filename: flava_tests
            monitor: label_validate_auroc
            mode: max
            save_top_k: 1
            every_n_epochs: 1
            save_last: True
        - class_path: lightning.pytorch.callbacks.EarlyStopping
          init_args:
            monitor: label_validate_auroc
            patience: 5
            mode: max
