defaults: &defaults
  metrics:
    - name: Accuracy
      args:
        task: multiclass
    - name: AUROC
      args:
        task: multiclass

models:
  flava:
    class_path: models.flava.FlavaClassificationModel
    init_args:
      model_class_or_path: facebook/flava-full
      <<: *defaults

  lxmert:
    class_path: models.lxmert.LxmertClassificationModel
    init_args:
      model_class_or_path: unc-nlp/lxmert-base-uncased
      <<: *defaults

  visualbert:
    class_path: models.visualbert.VisualBertClassificationModel
    init_args:
      model_class_or_path: uclanlp/visualbert-vqa-coco-pre
      <<: *defaults

  t5:
    class_path: models.t5.T5ClassificationModel
    init_args:
      model_class_or_path: t5-large
      <<: *defaults
      
  bart:
    class_path: models.bart.BARTCasualModel
    init_args:
      model_class_or_path: facebook/bart-large
      <<: *defaults