fhm:
  flava:
    cls_dict:
      label: 2
  lxmert:
    cls_dict:
      label: 2
  visualbert:
    cls_dict:
      label: 2
  bart:
    label2word:
      0: "no"
      1: "yes"
    labels:
      - label
  t5:
    label2word:
      0: "no"
      1: "yes"
    labels:
      - label

fhm_finegrained:
  flava:
    cls_dict:
      hate: 2
  lxmert:
    cls_dict:
      hate: 2
  bart:
    label2word:
      0: "no"
      1: "yes"
    labels:
      - hate
  visualbert:
    cls_dict:
      hate: 2
  t5:
    label2word:
      0: "no"
      1: "yes"
    labels:
      - hate

harmemes:
  intensity:
    flava:
      cls_dict:
        intensity: 3
    lxmert:
      cls_dict:
        intensity: 3
    visualbert:
      cls_dict:
        intensity: 3
    bart:
      label2word:
        0: "no"
        1: "yes"
        2: "yes"
      labels:
        - intensity
    t5:
      label2word:
        0: "no"
        1: "yes"
        2: "yes"
      labels:
        - intensity

  target:
    flava:
      cls_dict:
        target: 4
    lxmert:
      cls_dict:
        target: 4
    visualbert:
      cls_dict:
        target: 4
    bart:
      label2word:
        0: individual
        1: organization
        2: community
        3: society
      labels:
        - target
    t5:
      label2word:
        0: individual
        1: organization
        2: community
        3: society
      labels:
        - target
mami:
  subtask_a:
    flava:
      cls_dict:
        misogynous: 2
    lxmert:
      cls_dict:
        misogynous: 2
    visualbert:
      cls_dict:
        misogynous: 2
    bart:
      label2word:
        0: "no"
        1: "yes"
      labels:
        - misogynous
    t5:
      label2word:
        0: "no"
        1: "yes"
      labels:
        - misogynous
  subtask_b:
    flava:
      cls_dict:
        objectification: 2
        shaming: 2
        stereotype: 2
        violence: 2
    lxmert:
      cls_dict:
        objectification: 2
        shaming: 2
        stereotype: 2
        violence: 2
    visualbert:
      cls_dict:
        objectification: 2
        shaming: 2
        stereotype: 2
        violence: 2
    bart:
      label2word:
        0: "no"
        1: "yes"
      labels:
        - shaming
        - objectification
        - violence
        - stereotype
    t5:
      label2word:
        0: "no"
        1: "yes"
      labels:
        - shaming
        - objectification
        - violence
        - stereotype
harmp:
  intensity:
    flava:
      cls_dict:
        intensity: 3
    lxmert:
      cls_dict:
        intensity: 3
    visualbert:
      cls_dict:
        intensity: 3
    bart:
      label2word:
        0: "no"
        1: "yes"
        2: "yes"
      labels:
        - intensity
    t5:
      label2word:
        0: "no"
        1: "yes"
        2: "yes"
      labels:
        - intensity

  target:
    flava:
      cls_dict:
        target: 4
    lxmert:
      cls_dict:
        target: 4
    visualbert:
      cls_dict:
        target: 4
    bart:
      label2word:
        0: individual
        1: organization
        2: community
        3: society
      labels:
        - target
    t5:
      label2word:
        0: individual
        1: organization
        2: community
        3: society
      labels:
        - target
