trainers:
  bart:
    trainer:
      accelerator: gpu
      devices: 1
      max_epochs: 30
      accumulate_grad_batches: 1
      enable_checkpointing: True
      logger:
        class_path: lightning.pytorch.loggers.TensorBoardLogger
        init_args:
          save_dir: lightning_logs/
          name: harmeme/target
          version: bart_epochs30_date1007
          default_hp_metric: false
      callbacks:
        - class_path: lightning.pytorch.callbacks.ModelCheckpoint
          init_args:
            dirpath: checkpoints/bart/harmeme/target
            filename: bart_epochs30_date1007
            monitor: val_auroc
            mode: max
            save_top_k: 1
            every_n_epochs: 1
            save_last: True
        - class_path: lightning.pytorch.callbacks.EarlyStopping
          init_args:
            monitor: val_auroc
            patience: 5
            mode: max
  flava:
    trainer:
      accelerator: gpu
      devices: 1
      max_epochs: 30
      accumulate_grad_batches: 1
      enable_checkpointing: True
      logger:
        class_path: lightning.pytorch.loggers.TensorBoardLogger
        init_args:
          save_dir: lightning_logs/
          name: harmeme/target
          version: flava_epochs30_date1007
          default_hp_metric: false
      callbacks:
        - class_path: lightning.pytorch.callbacks.ModelCheckpoint
          init_args:
            dirpath: checkpoints/flava/harmeme/target
            filename: flava_epochs30_date1007
            monitor: target_validate_AUROC
            mode: max
            save_top_k: 1
            every_n_epochs: 1
            save_last: True
        - class_path: lightning.pytorch.callbacks.EarlyStopping
          init_args:
            monitor: target_validate_AUROC
            patience: 5
            mode: max

  lxmert:
    trainer:
      accelerator: gpu
      devices: 1
      max_epochs: 30
      accumulate_grad_batches: 1
      enable_checkpointing: True
      logger:
        class_path: lightning.pytorch.loggers.TensorBoardLogger
        init_args:
          save_dir: lightning_logs/
          name: harmeme/target
          version: lxmert_epochs30_date1007
          default_hp_metric: false
      callbacks:
        - class_path: lightning.pytorch.callbacks.ModelCheckpoint
          init_args:
            dirpath: checkpoints/lxmert_features/harmeme/target
            filename: lxmert_epochs30_date1007
            monitor: target_validate_AUROC
            mode: max
            save_top_k: 1
            every_n_epochs: 1
            save_last: True
        - class_path: lightning.pytorch.callbacks.EarlyStopping
          init_args:
            monitor: target_validate_AUROC
            patience: 5
            mode: max

  t5:
    trainer:
      accelerator: gpu
      devices: 1
      max_epochs: 30
      accumulate_grad_batches: 1
      enable_checkpointing: True
      logger:
        class_path: lightning.pytorch.loggers.TensorBoardLogger
        init_args:
          save_dir: lightning_logs/
          name: harmeme/target
          version: t5_epochs30_date1007
          default_hp_metric: false
      callbacks:
        - class_path: lightning.pytorch.callbacks.ModelCheckpoint
          init_args:
            dirpath: checkpoints/t5/harmeme/target
            filename: t5_epochs30_date1007
            monitor: val_auroc
            mode: max
            save_top_k: 1
            every_n_epochs: 1
            save_last: True
        - class_path: lightning.pytorch.callbacks.EarlyStopping
          init_args:
            monitor: val_auroc
            patience: 5
            mode: max

  visualbert:
    trainer:
      accelerator: gpu
      devices: 1
      max_epochs: 30
      accumulate_grad_batches: 1
      enable_checkpointing: True
      logger:
        class_path: lightning.pytorch.loggers.TensorBoardLogger
        init_args:
          save_dir: lightning_logs/
          name: harmeme/target
          version: visualbert_epochs30_date1007
          default_hp_metric: false
      callbacks: 
        - class_path: lightning.pytorch.callbacks.ModelCheckpoint
          init_args:
            dirpath: checkpoints/visualbert_features/harmeme/target
            filename: visualbert_epochs30_date1007
            monitor: target_validate_AUROC
            mode: max
            save_top_k: 1
            every_n_epochs: 1
            save_last: True
        - class_path: lightning.pytorch.callbacks.EarlyStopping
          init_args:
            monitor: target_validate_AUROC
            patience: 5
            mode: max