auxiliary_dicts: {}
shuffle_train: true
num_workers: 4
batch_size: 32
dataset_class: datamodules.datasets.fhm.FasterRCNNDataset
tokenizer_class_or_path: ${{ parameters.models_name[0] }}

parameters:
  models_name: ???