# lightning.pytorch==2.0.0
seed_everything: 1111
trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 30
  accumulate_grad_batches: 1
  enable_checkpointing: True
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: lightning_logs/
      name: harmeme
      version: flava_epochs30_date2306
      default_hp_metric: false
  callbacks: 
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: checkpoints/flava/harmeme/target
        filename: flava_epochs30_date2306
        monitor: target_validate_auroc
        mode: max
        save_top_k: 1
        every_n_epochs: 1
        save_last: True
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: target_validate_auroc
        patience: 5
        mode: max
model:
  class_path: models.flava.FlavaClassificationModel
  init_args:
    model_class_or_path: facebook/flava-full
    cls_dict: {
      "target": 4
    }
data:
  class_path: datamodules.modules.ImagesDataModule
  init_args:
    tokenizer_class_or_path: facebook/flava-full
    frcnn_class_or_path: None
    dataset_class: datamodules.datasets.harmemes.ImagesDataset
    image_dirs: {
      train: /mnt/sda/datasets/memes/harmemes/images,
      validate: /mnt/sda/datasets/memes/harmemes/images,
      test: /mnt/sda/datasets/memes/harmemes/images,
      predict: /mnt/sda/datasets/memes/harmemes/images,
    }
    annotation_filepaths: {
      train: /mnt/sda/datasets/memes/harmemes/annotations/train.jsonl,
      validate: /mnt/sda/datasets/memes/harmemes/annotations/val.jsonl,
      test: /mnt/sda/datasets/memes/harmemes/annotations/test.jsonl,
      predict: /mnt/sda/datasets/memes/harmemes/annotations/test.jsonl,
    }
    auxiliary_dicts: {}
    shuffle_train: True
    labels:
    - target
    batch_size: 32
    num_workers: 8