# lightning.pytorch==2.0.0
seed_everything: 1111
trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 30
  accumulate_grad_batches: 1
  enable_checkpointing: True
  callbacks: 
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: checkpoints/flavas/harmeme/intensity
        monitor: intensity_validate_auroc
        mode: max
        save_top_k: 1
        every_n_epochs: 1
        save_last: True
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: intensity_validate_auroc
        patience: 5
        mode: max
model:
  class_path: models.flava.FlavaClassificationModel
  init_args:
    model_class_or_path: facebook/flava-full
    cls_dict: {
      "intensity": 3
    }
data:
  class_path: datamodules.modules.ImagesDataModule
  init_args:
    tokenizer_class_or_path: facebook/flava-full
    frcnn_class_or_path: None
    dataset_class: datamodules.datasets.harmemes.ImagesDataset
    image_dirs: {
      train: /mnt/sda/datasets/memes/harmemes/images,
      validate: /mnt/sda/datasets/memes/harmemes/images,
      test: /mnt/sda/datasets/memes/harmemes/images,
      predict: /mnt/sda/datasets/memes/harmemes/images,
    }
    annotation_filepaths: {
      train: /mnt/sda/datasets/memes/harmemes/annotations/original/train.jsonl,
      validate: /mnt/sda/datasets/memes/harmemes/annotations/original/val.jsonl,
      test: /mnt/sda/datasets/memes/harmemes/annotations/original/test.jsonl,
      predict: /mnt/sda/datasets/memes/harmemes/annotations/original/test.jsonl,
    }
    auxiliary_dicts: {
      # "caption": "/mnt/sda/datasets/memes/fhm/captions/fhm_clean_captions.pkl"
    }
    shuffle_train: True
    labels:
    - intensity
    batch_size: 32
    num_workers: 8