# lightning.pytorch==2.0.0
seed_everything: 1111
trainer:
  default_root_dir: lightning_logs/lxmert_features/harmeme/intensity
  accelerator: gpu
  devices: 1
  max_epochs: 30
  accumulate_grad_batches: 1
  enable_checkpointing: True
  callbacks: 
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: checkpoints/lxmert_features/harmeme/intensity
        monitor: intensity_validate_auroc
        mode: max
        save_top_k: 1
        every_n_epochs: 1
        save_last: True
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: intensity_validate_auroc
        patience: 5
        mode: max

model:
  class_path: models.lxmert.LxmertClassificationModel
  init_args:
    model_class_or_path: unc-nlp/lxmert-base-uncased
    cls_dict: {
      "intensity": 3
    }
data:
  class_path: datamodules.VLFeaturesDataModule
  init_args:
    tokenizer_class_or_path: unc-nlp/lxmert-base-uncased
    feats_dirs: {
      train: /Scratch/datasets/harmemes/features/unc-nlp/frcnn-vg-finetuned,
      validate: /Scratch/datasets/harmemes/features/unc-nlp/frcnn-vg-finetuned,
      test: /Scratch/datasets/harmemes/features/unc-nlp/frcnn-vg-finetuned,
      predict: /Scratch/datasets/harmemes/features/unc-nlp/frcnn-vg-finetuned
    }
    annotation_filepaths: {
      train: /Scratch/datasets/harmemes/annotations/train.jsonl,
      validate: /Scratch/datasets/harmemes/annotations/val.jsonl,
      test: /Scratch/datasets/harmemes/annotations/test.jsonl,
      predict: /Scratch/datasets/harmemes/annotations/val.jsonl
    }
    shuffle_train: True
    batch_size: 32
    labels:
    - intensity