# lightning.pytorch==2.0.0
seed_everything: 1111
trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 30
  accumulate_grad_batches: 1
  enable_checkpointing: True
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: lightning_logs/
      name: harmeme
      version: visualbert_epochs30_date2306
      default_hp_metric: false
  callbacks: 
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: checkpoints/visualbert_features/harmeme/intensity
        filename: visualbert_epochs30_date2306
        monitor: intensity_validate_auroc
        mode: max
        save_top_k: 1
        every_n_epochs: 1
        save_last: True
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: intensity_validate_auroc
        patience: 5
        mode: max
model:
  class_path: models.visualbert.VisualBertClassificationModel
  init_args:
    model_class_or_path: uclanlp/visualbert-vqa-coco-pre
    cls_dict: {
      "intensity": 3
    }
data:
  class_path: datamodules.modules.FasterRCNNDataModule
  init_args:
    tokenizer_class_or_path: bert-base-uncased
    dataset_class: datamodules.datasets.harmemes.FasterRCNNDataset
    feats_dirs: {
      train: /mnt/sdb/aditi/datasets/harmemes/features/unc-nlp/frcnn-vg-finetuned,
      validate: /mnt/sdb/aditi/datasets/harmemes/features/unc-nlp/frcnn-vg-finetuned,
      test: /mnt/sdb/aditi/datasets/harmemes/features/unc-nlp/frcnn-vg-finetuned,
      predict: /mnt/sdb/aditi/datasets/harmemes/features/unc-nlp/frcnn-vg-finetuned,
    }
    annotation_filepaths: {
      train: /mnt/sdb/aditi/mmf/data/datasets/memes/defaults/annotations/train.jsonl,
      validate: /mnt/sdb/aditi/mmf/data/datasets/memes/defaults/annotations/val.jsonl,
      test: /mnt/sdb/aditi/mmf/data/datasets/memes/defaults/annotations/test.jsonl,
      predict: /mnt/sdb/aditi/mmf/data/datasets/memes/defaults/annotations/test.jsonl,
    }
    auxiliary_dicts: {
      # "caption": "/mnt/sda/datasets/memes/fhm/captions/fhm_clean_captions.pkl"
    }
    shuffle_train: True
    batch_size: 4
    labels:
    - intensity
    num_workers: 8